apiVersion: apps/v1
kind: Deployment
metadata:
  name: vs-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vs-app
  template:
    metadata:
      labels:
        app: vs-app
    spec:
      containers:
      - name: vs-app
        image: krosf/vs:sqlite
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: vs-app-svc
  labels:
    app: vs-app
spec:
  type: ClusterIP
  selector:
    app: vs-app
  ports:
  - name: http
    port: 8080
    targetPort: 8080
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: vs
  namespace: vs
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`vs.intl.krosf.com`)
      kind: Rule
      services:
        - name: vs-app-svc
          port: 8080
  tls:
    certResolver: cloudflare