apiVersion: v1
kind: Secret
metadata:
  name: vs-secrets
  namespace: vs
type: Opaque
stringData:
  DATABASE_NAME: vs
  DATABASE_USERNAME: vs
  DATABASE_PASSWORD: kuljjogXGpT0G0IyTkSHdF8Any2ICBxZ
---
apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secrets
  namespace: vs
type: Opaque
stringData:
  MARIADB_USER: vs
  MARIADB_DATABASE: vs
  MARIADB_PASSWORD: kuljjogXGpT0G0IyTkSHdF8Any2ICBxZ
  MARIADB_ROOT_PASSWORD: WjlJd9kcbFRTv7QVdyxgHWSsNxgtYP5l